// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	context "context"

	bingboop "github.com/dooven/bingboop"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// SearchDocument provides a mock function with given fields: ctx, vaultID, filter
func (_m *Client) SearchDocument(ctx context.Context, vaultID string, filter bingboop.SearchFilter) (bingboop.SearchDocumentResult, error) {
	ret := _m.Called(ctx, vaultID, filter)

	var r0 bingboop.SearchDocumentResult
	if rf, ok := ret.Get(0).(func(context.Context, string, bingboop.SearchFilter) bingboop.SearchDocumentResult); ok {
		r0 = rf(ctx, vaultID, filter)
	} else {
		r0 = ret.Get(0).(bingboop.SearchDocumentResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, bingboop.SearchFilter) error); ok {
		r1 = rf(ctx, vaultID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
