// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	url "net/url"

	mock "github.com/stretchr/testify/mock"
)

// URLBuilder is an autogenerated mock type for the URLBuilder type
type URLBuilder struct {
	mock.Mock
}

// CreateAccessTokenURL provides a mock function with given fields: userId
func (_m *URLBuilder) CreateAccessTokenURL(userId string) string {
	ret := _m.Called(userId)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CreateApiKeyURL provides a mock function with given fields: userId
func (_m *URLBuilder) CreateApiKeyURL(userId string) string {
	ret := _m.Called(userId)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CreateUserURL provides a mock function with given fields:
func (_m *URLBuilder) CreateUserURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DeleteUserURL provides a mock function with given fields: userId
func (_m *URLBuilder) DeleteUserURL(userId string) string {
	ret := _m.Called(userId)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUserURL provides a mock function with given fields: userId
func (_m *URLBuilder) GetUserURL(userId []string) string {
	ret := _m.Called(userId)

	var r0 string
	if rf, ok := ret.Get(0).(func([]string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ListUserURL provides a mock function with given fields: queryParams
func (_m *URLBuilder) ListUserURL(queryParams url.Values) string {
	ret := _m.Called(queryParams)

	var r0 string
	if rf, ok := ret.Get(0).(func(url.Values) string); ok {
		r0 = rf(queryParams)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SearchDocumentURL provides a mock function with given fields: vaultID
func (_m *URLBuilder) SearchDocumentURL(vaultID string) string {
	ret := _m.Called(vaultID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(vaultID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UpdateUserPasswordURL provides a mock function with given fields: userId
func (_m *URLBuilder) UpdateUserPasswordURL(userId string) string {
	ret := _m.Called(userId)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UpdateUserURL provides a mock function with given fields: userId
func (_m *URLBuilder) UpdateUserURL(userId string) string {
	ret := _m.Called(userId)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
