// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLBuilder is an autogenerated mock type for the URLBuilder type
type URLBuilder struct {
	mock.Mock
}

// SearchDocumentURL provides a mock function with given fields: vaultID
func (_m *URLBuilder) SearchDocumentURL(vaultID string) string {
	ret := _m.Called(vaultID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(vaultID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
