---
name: Go
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: 'Run Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
      - run: go test -v -race
